Adding option to display similar names to the package entered
sindresorhus/npm-name-cli pull request #23
Opened 2020-10-31 21:32 UTC by Robbie-Cook

This is in response to the conversation in #22 .

Now, the usage can be `npm-name hello --similar`.

2020-12-24 09:19 UTC, sindresorhus commented
Can you also update the FAQ section in the readme? https://github.com/sindresorhus/npm-name-cli#why-would-i-use-npm-name-rather-than-npms-built-in-search

2020-12-24 09:26 UTC, sindresorhus requested changes

2020-12-24 09:26 UTC, sindresorhus commented on package.json
> +			"no-await-in-loop": [0]
It's better to use an inline `// eslint-disable` comment for this.

2020-12-24 09:26 UTC, sindresorhus commented on util.js
> +	if (pkg.name) {
Use an early-return.

2020-12-24 09:26 UTC, sindresorhus commented on util.js
> +		if (names) {
Use an early-return.

2020-12-24 09:26 UTC, sindresorhus commented on util.js
> + *
I prefer not to use the `*` border.

2020-12-24 09:26 UTC, sindresorhus commented on util.js
> + *
https://github.com/sindresorhus/typescript-definition-style-guide

2020-12-24 09:26 UTC, sindresorhus commented on package.json
> +		"slugify": "^1.4.5",
Use https://github.com/sindresorhus/slugify

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +			packages.every(pkg => Boolean(pkg.isAvailable || pkg.isSquatter)) ? 0	: 2
```suggestion
			packages.every(pkg => Boolean(pkg.isAvailable || pkg.isSquatter)) ? 0 : 2
```

2020-12-24 09:26 UTC, sindresorhus commented on util.js
> +const squatter = require('squatter');
You need to add this file to `files` in package.json.

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +		$ npm-name <name> …
Don't do unrelated changes.

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +		${logSymbols.success} ${chalk.bold('bigcactus')} is available;
Incorrect indentation.

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +		${logSymbols.warning} ${chalk.bold('bigiron')} is unavailable
You also need to update the readme output.

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +).start();
Don't do unrelated changes.

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +	if (packages) {
Invert this condition to reduce nesting.

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +		for (const pkg of packages) {
```suggestion
		for (const package_ of packages) {
```

2020-12-24 09:26 UTC, sindresorhus commented on cli.js
> +		--similar  Find similar package names
```suggestion
		--similar  Find similar package names too
```

2021-01-21 21:56 UTC, Robbie-Cook commented
Sorry, but I'm not comfortable working on this PR. I am not going to make those changes you requested. Feel free to close this.
That being said, please use this PR how you like, anyone. Would love to see a fixed version of this merged in.

2021-01-22 17:56 UTC, sindresorhus commented
> Sorry, but I'm not comfortable working on this PR.

Any reason why?

2021-01-22 17:57 UTC, closed without merging